---
- name: Ensure Initial Configuration on Ubuntu systems
  hosts: all
  connection: ssh
  become: true
  roles:
    - role: geerlingguy.mysql
    
  tasks:
  
    - name: display post install message
      debug:
        msg:
          - 'This playbook is for installing MySQL for the Zabbix Database server.'
          - 'If successful, you should still run installation for Zabbix Frontend.'
